// src/renderer/src/components/StatusBar.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue'
import { storeToRefs } from 'pinia'
import { useTabsStore } from '../stores/tabsStore'
import './StatusBar.css'

const appVersion = ref<string>('')

const tabsStore = useTabsStore()
const { tabs, activeTabId, showHomePage } = storeToRefs(tabsStore)

const currentTabName = computed((): string => {
  if (showHomePage.value) return 'Home'
  const activeTab = tabs.value.find((tab) => tab.id === activeTabId.value)
  if (!activeTab) return 'Ready'
  return activeTab.title
})

onMounted(async () => {
  try {
    appVersion.value = await window.api.getAppVersion()
  } catch (error) {
    console.error('Failed to get app version:', error)
    appVersion.value = 'Unknown'
  }
})
</script>

<template>
  <div class="status-bar">
    <div class="status-item">{{ currentTabName }}</div>
    <div class="status-item">v{{ appVersion }}</div>
  </div>
</template>

// src/renderer/src/components/StatusBar.tsx
import React, { useState, useEffect, useCallback } from 'react'
import { useTabsStore } from '../stores/tabsStore'
import './StatusBar.css'

const StatusBar: React.FC = () => {
  const [appVersion, setAppVersion] = useState<string>('')

  // Get state from the tabs store
  const { activeTabId, tabs, showHomePage } = useTabsStore()

  // Get app version on mount
  useEffect(() => {
    const getVersion = async (): Promise<void> => {
      try {
        const version = await window.api.getAppVersion()
        setAppVersion(version)
      } catch (error) {
        console.error('Failed to get app version:', error)
        setAppVersion('Unknown')
      }
    }

    getVersion()
  }, [])

  // Get the current tab name or show Home if home page is active
  const getCurrentTabName = useCallback((): string => {
    if (showHomePage) {
      return 'Home'
    }

    const activeTab = tabs.find((tab) => tab.id === activeTabId)
    if (!activeTab) {
      return 'Ready'
    }

    return activeTab.title
  }, [activeTabId, showHomePage, tabs])

  return (
    <div className="status-bar">
      <div className="status-item">{getCurrentTabName()}</div>
      <div className="status-item">v{appVersion}</div>
    </div>
  )
}

export default StatusBar
