// src/renderer/src/components/TabBar.vue
<script setup lang="ts">
import { ref, computed, watch, onMounted, onUnmounted, nextTick } from 'vue'
import { storeToRefs } from 'pinia'
import { useTabsStore } from '../stores/tabsStore'
import './TabBar.css'

const props = defineProps<{
  isHomeActive: boolean
  onShowHome: () => void
  onHideHome: () => void
}>()

const tabsStore = useTabsStore()
const { tabs, activeTabId } = storeToRefs(tabsStore)
const { setActiveTab, closeTab, closeOtherTabs, closeAllTabs, closeTabsToRight, reorderTabs } =
  tabsStore

const tabsContainerRef = ref<HTMLDivElement | null>(null)
const tabRefs = ref<(HTMLDivElement | null)[]>([])

const setTabRef = (el: Element | null, index: number): void => {
  tabRefs.value[index] = el as HTMLDivElement | null
}

const draggedTab = ref<string | null>(null)
const draggedIndex = ref<number>(-1)
const dropIndicatorLeft = ref<number>(0)
const isDragging = ref<boolean>(false)

const contextMenuVisible = ref<boolean>(false)
const contextMenuPosition = ref<{ x: number; y: number }>({ x: 0, y: 0 })
const contextMenuTabId = ref<string | null>(null)

const showScrollButtons = ref<boolean>(false)

const tabDensity = computed<'compact' | 'medium' | 'wide'>(() => {
  if (tabs.value.length > 10) return 'compact'
  if (tabs.value.length > 5) return 'medium'
  return 'wide'
})

const checkScrollButtonsVisibility = (): void => {
  const container = tabsContainerRef.value
  if (!container) return
  showScrollButtons.value = container.scrollWidth > container.clientWidth
}

watch(
  tabs,
  () => {
    tabRefs.value = tabRefs.value.slice(0, tabs.value.length)
    nextTick(() => checkScrollButtonsVisibility())
  },
  { deep: true }
)

const handleResize = (): void => {
  checkScrollButtonsVisibility()
}

const handleKeyDown = (e: KeyboardEvent): void => {
  if (e.ctrlKey && e.key === 'Tab') {
    e.preventDefault()
    if (tabs.value.length > 0) {
      const currentIndex = tabs.value.findIndex((tab) => tab.id === activeTabId.value)
      const nextIndex = (currentIndex + 1) % tabs.value.length
      setActiveTab(tabs.value[nextIndex].id)
      props.onHideHome()
    }
  }

  if (e.ctrlKey && e.shiftKey && e.key === 'Tab') {
    e.preventDefault()
    if (tabs.value.length > 0) {
      const currentIndex = tabs.value.findIndex((tab) => tab.id === activeTabId.value)
      const prevIndex = (currentIndex - 1 + tabs.value.length) % tabs.value.length
      setActiveTab(tabs.value[prevIndex].id)
      props.onHideHome()
    }
  }

  if (e.ctrlKey && !e.shiftKey && !e.altKey && /^[1-9]$/.test(e.key)) {
    const tabIndex = parseInt(e.key) - 1
    if (tabIndex < tabs.value.length) {
      e.preventDefault()
      setActiveTab(tabs.value[tabIndex].id)
      props.onHideHome()
    }
  }

  if ((e.ctrlKey || e.metaKey) && !e.shiftKey && !e.altKey && e.key.toLowerCase() === 'w') {
    if (activeTabId.value && !props.isHomeActive) {
      e.preventDefault()
      closeTab(activeTabId.value)
    }
  }

  if ((e.ctrlKey || e.metaKey) && !e.shiftKey && !e.altKey && e.key.toLowerCase() === 'h') {
    e.preventDefault()
    props.onShowHome()
  }
}

const handleClickOutsideContext = (): void => {
  contextMenuVisible.value = false
}

const handleTabKeydown = (e: KeyboardEvent, tabId: string): void => {
  if (e.key === 'Enter' || e.key === ' ') {
    e.preventDefault()
    handleTabClick(tabId)
  }
}

const handleContextMenuKeydown = (e: KeyboardEvent, action: () => void): void => {
  if (e.key === 'Enter' || e.key === ' ') {
    e.preventDefault()
    action()
  } else if (e.key === 'Escape') {
    contextMenuVisible.value = false
  }
}

onMounted(() => {
  window.addEventListener('resize', handleResize)
  window.addEventListener('keydown', handleKeyDown)
  document.addEventListener('click', handleClickOutsideContext)
  nextTick(() => checkScrollButtonsVisibility())
})

onUnmounted(() => {
  window.removeEventListener('resize', handleResize)
  window.removeEventListener('keydown', handleKeyDown)
  document.removeEventListener('click', handleClickOutsideContext)
})

const scrollLeft = (): void => {
  const container = tabsContainerRef.value
  if (!container) return
  const newPosition = Math.max(0, container.scrollLeft - 200)
  container.scrollTo({ left: newPosition, behavior: 'smooth' })
}

const scrollRight = (): void => {
  const container = tabsContainerRef.value
  if (!container) return
  const newPosition = Math.min(
    container.scrollWidth - container.clientWidth,
    container.scrollLeft + 200
  )
  container.scrollTo({ left: newPosition, behavior: 'smooth' })
}

const handleTabClick = (tabId: string): void => {
  setActiveTab(tabId)
  props.onHideHome()
}

const handleCloseTab = (e: MouseEvent, tabId: string): void => {
  e.stopPropagation()
  closeTab(tabId)
}

const handleContextMenu = (e: MouseEvent, tabId: string): void => {
  e.preventDefault()
  contextMenuTabId.value = tabId
  contextMenuPosition.value = { x: e.clientX, y: e.clientY }
  contextMenuVisible.value = true
}

const handleCloseOtherTabs = (): void => {
  if (contextMenuTabId.value) {
    closeOtherTabs(contextMenuTabId.value)
  }
  contextMenuVisible.value = false
}

const handleCloseAllTabs = (): void => {
  closeAllTabs()
  contextMenuVisible.value = false
}

const handleCloseTabsToRight = (): void => {
  if (contextMenuTabId.value) {
    closeTabsToRight(contextMenuTabId.value)
  }
  contextMenuVisible.value = false
}

const handleHomeClick = (): void => {
  props.onShowHome()
}

const handleDragStart = (e: DragEvent, tabId: string, index: number): void => {
  draggedTab.value = tabId
  draggedIndex.value = index
  isDragging.value = true

  if (e.dataTransfer && tabRefs.value[index]) {
    e.dataTransfer.setDragImage(tabRefs.value[index]!, 0, 0)
    e.dataTransfer.effectAllowed = 'move'
  }
}

const handleDragOver = (e: DragEvent, _tabId: string, index: number): void => {
  e.preventDefault()
  if (!isDragging.value || draggedTab.value === null) return

  const tabElement = tabRefs.value[index]
  if (tabElement) {
    const rect = tabElement.getBoundingClientRect()
    const mouseX = e.clientX
    const containerLeft = tabsContainerRef.value?.getBoundingClientRect().left || 0

    if (mouseX < rect.left + rect.width / 2) {
      dropIndicatorLeft.value = rect.left - containerLeft
    } else {
      dropIndicatorLeft.value = rect.right - containerLeft
    }
  }
}

const handleDrop = (e: DragEvent, index: number): void => {
  e.preventDefault()
  if (draggedIndex.value === index || draggedTab.value === null) return

  const tabElement = tabRefs.value[index]
  if (tabElement) {
    const rect = tabElement.getBoundingClientRect()
    const mouseX = e.clientX
    let dropIndex = index
    if (mouseX > rect.left + rect.width / 2) {
      dropIndex += 1
    }
    if (draggedIndex.value < dropIndex) {
      dropIndex -= 1
    }
    reorderTabs(draggedIndex.value, dropIndex)
  }

  draggedTab.value = null
  draggedIndex.value = -1
  isDragging.value = false
}

const handleDragEnd = (): void => {
  draggedTab.value = null
  draggedIndex.value = -1
  isDragging.value = false
}
</script>

<template>
  <div class="tabs-container" :data-density="tabDensity">
    <button
      class="home-button"
      :class="{ active: isHomeActive }"
      title="Home"
      @click="handleHomeClick"
    >
      Home
    </button>

    <div class="tabs-rows-container">
      <button
        v-if="showScrollButtons"
        class="tab-scroll-button tab-scroll-left"
        @click="scrollLeft"
      >
        &lt;
      </button>

      <div
        ref="tabsContainerRef"
        class="tabs-scroll-area"
        role="tablist"
        aria-label="Open transformation tabs"
      >
        <div
          v-if="isDragging"
          class="drop-indicator"
          :style="{ left: `${dropIndicatorLeft}px` }"
        ></div>

        <div
          v-for="(tab, index) in tabs"
          :key="tab.id"
          :ref="(el) => setTabRef(el as Element | null, index)"
          class="tab"
          :class="{
            active: tab.id === activeTabId && !isHomeActive,
            inactive: isHomeActive,
            dragging: draggedTab === tab.id
          }"
          role="tab"
          :tabindex="tab.id === activeTabId && !isHomeActive ? 0 : -1"
          :aria-selected="tab.id === activeTabId && !isHomeActive"
          draggable="true"
          @click="handleTabClick(tab.id)"
          @keydown="handleTabKeydown($event, tab.id)"
          @contextmenu="handleContextMenu($event, tab.id)"
          @dragstart="handleDragStart($event, tab.id, index)"
          @dragover="handleDragOver($event, tab.id, index)"
          @drop="handleDrop($event, index)"
          @dragend="handleDragEnd"
        >
          <div class="tab-title">{{ tab.title }}</div>
          <button
            class="tab-close"
            type="button"
            :aria-label="`Close ${tab.title}`"
            @click="handleCloseTab($event, tab.id)"
          >
            ✕
          </button>
        </div>
      </div>

      <button
        v-if="showScrollButtons"
        class="tab-scroll-button tab-scroll-right"
        @click="scrollRight"
      >
        &gt;
      </button>
    </div>

    <div
      v-if="contextMenuVisible && contextMenuTabId"
      class="tab-context-menu"
      role="menu"
      :style="{
        top: `${contextMenuPosition.y}px`,
        left: `${contextMenuPosition.x}px`
      }"
    >
      <div
        class="context-menu-item"
        role="menuitem"
        tabindex="0"
        @click="
          () => {
            if (contextMenuTabId) closeTab(contextMenuTabId)
            contextMenuVisible = false
          }
        "
        @keydown="
          handleContextMenuKeydown($event, () => {
            if (contextMenuTabId) closeTab(contextMenuTabId)
            contextMenuVisible = false
          })
        "
      >
        Close
      </div>
      <div
        class="context-menu-item"
        role="menuitem"
        tabindex="0"
        @click="handleCloseOtherTabs"
        @keydown="handleContextMenuKeydown($event, handleCloseOtherTabs)"
      >
        Close Others
      </div>
      <div
        class="context-menu-item"
        role="menuitem"
        tabindex="0"
        @click="handleCloseTabsToRight"
        @keydown="handleContextMenuKeydown($event, handleCloseTabsToRight)"
      >
        Close Tabs to the Right
      </div>
      <div
        class="context-menu-item"
        role="menuitem"
        tabindex="0"
        @click="handleCloseAllTabs"
        @keydown="handleContextMenuKeydown($event, handleCloseAllTabs)"
      >
        Close All
      </div>
    </div>
  </div>
</template>

// src/renderer/src/components/TabBar.tsx
import React, { useRef, useState, useEffect, useCallback } from 'react'
import { useTabsStore } from '../stores/tabsStore'
import './TabBar.css'

interface TabBarProps {
  isHomeActive: boolean
  onShowHome: () => void
  onHideHome: () => void
}

const TabBar: React.FC<TabBarProps> = ({ isHomeActive, onShowHome, onHideHome }) => {
  const {
    tabs,
    activeTabId,
    setActiveTab,
    closeTab,
    closeOtherTabs,
    closeAllTabs,
    closeTabsToRight,
    reorderTabs
  } = useTabsStore()

  // Refs for DOM elements
  const tabsContainerRef = useRef<HTMLDivElement>(null)
  const tabRefs = useRef<(HTMLDivElement | null)[]>([])

  // Drag and drop state
  const [draggedTab, setDraggedTab] = useState<string | null>(null)
  const [draggedIndex, setDraggedIndex] = useState<number>(-1)
  const [dropIndicatorLeft, setDropIndicatorLeft] = useState<number>(0)
  const [isDragging, setIsDragging] = useState<boolean>(false)

  // Context menu state
  const [contextMenuVisible, setContextMenuVisible] = useState<boolean>(false)
  const [contextMenuPosition, setContextMenuPosition] = useState<{ x: number; y: number }>({
    x: 0,
    y: 0
  })
  const [contextMenuTabId, setContextMenuTabId] = useState<string | null>(null)

  // Scroll state
  const [showScrollButtons, setShowScrollButtons] = useState<boolean>(false)

  // Check if scroll buttons should be shown and adjust tab widths
  const checkScrollButtonsVisibility = useCallback((): void => {
    if (!tabsContainerRef.current) return

    const container = tabsContainerRef.current
    const shouldShowButtons = container.scrollWidth > container.clientWidth

    // Adjust tab widths based on number of tabs
    const tabElements = container.querySelectorAll('.tab')
    if (tabElements.length > 0) {
      // Apply different max-width based on number of tabs
      let maxWidth = '200px'
      if (tabs.length > 10) {
        maxWidth = '120px'
      } else if (tabs.length > 5) {
        maxWidth = '160px'
      }

      tabElements.forEach((tab) => {
        ;(tab as HTMLElement).style.maxWidth = maxWidth
      })
    }

    setShowScrollButtons(shouldShowButtons)
  }, [tabs.length])

  // Reset tab refs when tabs change
  useEffect(() => {
    tabRefs.current = tabRefs.current.slice(0, tabs.length)

    // Check if scroll buttons should be shown
    checkScrollButtonsVisibility()
  }, [tabs, checkScrollButtonsVisibility])

  // Check scroll buttons visibility when window is resized
  useEffect(() => {
    const handleResize = (): void => {
      checkScrollButtonsVisibility()
    }

    window.addEventListener('resize', handleResize)
    return () => {
      window.removeEventListener('resize', handleResize)
    }
  }, [tabs, checkScrollButtonsVisibility])

  // Add keyboard shortcuts for tab navigation
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent): void => {
      // Ctrl+Tab to switch to next tab
      if (e.ctrlKey && e.key === 'Tab') {
        e.preventDefault()
        if (tabs.length > 0) {
          const currentIndex = tabs.findIndex((tab) => tab.id === activeTabId)
          const nextIndex = (currentIndex + 1) % tabs.length
          setActiveTab(tabs[nextIndex].id)
          onHideHome()
        }
      }

      // Ctrl+Shift+Tab to switch to previous tab
      if (e.ctrlKey && e.shiftKey && e.key === 'Tab') {
        e.preventDefault()
        if (tabs.length > 0) {
          const currentIndex = tabs.findIndex((tab) => tab.id === activeTabId)
          const prevIndex = (currentIndex - 1 + tabs.length) % tabs.length
          setActiveTab(tabs[prevIndex].id)
          onHideHome()
        }
      }

      // Ctrl+1-9 to switch to specific tab
      if (e.ctrlKey && !e.shiftKey && !e.altKey && /^[1-9]$/.test(e.key)) {
        const tabIndex = parseInt(e.key) - 1
        if (tabIndex < tabs.length) {
          e.preventDefault()
          setActiveTab(tabs[tabIndex].id)
          onHideHome()
        }
      }
    }

    window.addEventListener('keydown', handleKeyDown)
    return () => {
      window.removeEventListener('keydown', handleKeyDown)
    }
  }, [tabs, activeTabId, setActiveTab, onHideHome])

  // Handle tab scrolling
  const scrollLeft = useCallback((): void => {
    if (tabsContainerRef.current) {
      const container = tabsContainerRef.current
      const newPosition = Math.max(0, container.scrollLeft - 200)
      container.scrollTo({ left: newPosition, behavior: 'smooth' })
    }
  }, [])

  const scrollRight = useCallback((): void => {
    if (tabsContainerRef.current) {
      const container = tabsContainerRef.current
      const newPosition = Math.min(
        container.scrollWidth - container.clientWidth,
        container.scrollLeft + 200
      )
      container.scrollTo({ left: newPosition, behavior: 'smooth' })
    }
  }, [])

  // Handle tab activation
  const handleTabClick = (tabId: string): void => {
    setActiveTab(tabId)
    onHideHome()
  }

  // Handle tab closing
  const handleCloseTab = (e: React.MouseEvent, tabId: string): void => {
    e.stopPropagation()
    closeTab(tabId)
  }

  // Handle context menu
  const handleContextMenu = (e: React.MouseEvent, tabId: string): void => {
    e.preventDefault()
    setContextMenuTabId(tabId)
    setContextMenuPosition({ x: e.clientX, y: e.clientY })
    setContextMenuVisible(true)
  }

  // Close context menu when clicking outside
  useEffect(() => {
    const handleClickOutside = (): void => {
      setContextMenuVisible(false)
    }

    if (contextMenuVisible) {
      document.addEventListener('click', handleClickOutside)
    }

    return () => {
      document.removeEventListener('click', handleClickOutside)
    }
  }, [contextMenuVisible])

  // Context menu actions
  const handleCloseOtherTabs = (): void => {
    if (contextMenuTabId) {
      closeOtherTabs(contextMenuTabId)
    }
    setContextMenuVisible(false)
  }

  const handleCloseAllTabs = (): void => {
    closeAllTabs()
    setContextMenuVisible(false)
  }

  const handleCloseTabsToRight = (): void => {
    if (contextMenuTabId) {
      closeTabsToRight(contextMenuTabId)
    }
    setContextMenuVisible(false)
  }

  // Handle home button click
  const handleHomeClick = (): void => {
    onShowHome()
  }

  // Drag and drop handlers
  const handleDragStart = (e: React.DragEvent, tabId: string, index: number): void => {
    setDraggedTab(tabId)
    setDraggedIndex(index)
    setIsDragging(true)

    // Set drag image (optional)
    if (e.dataTransfer && tabRefs.current[index]) {
      e.dataTransfer.setDragImage(tabRefs.current[index]!, 0, 0)
    }

    e.dataTransfer.effectAllowed = 'move'
  }

  const handleDragOver = (e: React.DragEvent, tabId: string, index: number): void => {
    e.preventDefault()

    if (!isDragging || draggedTab === null) return

    // Calculate drop position
    const tabElement = tabRefs.current[index]
    if (tabElement) {
      const rect = tabElement.getBoundingClientRect()
      const mouseX = e.clientX

      // Determine if we're on the left or right half of the tab
      if (mouseX < rect.left + rect.width / 2) {
        // Left half - place indicator at the left edge
        setDropIndicatorLeft(
          rect.left - (tabsContainerRef.current?.getBoundingClientRect().left || 0)
        )
      } else {
        // Right half - place indicator at the right edge
        setDropIndicatorLeft(
          rect.right - (tabsContainerRef.current?.getBoundingClientRect().left || 0)
        )
      }
    }
  }

  const handleDrop = (e: React.DragEvent, index: number): void => {
    e.preventDefault()

    if (draggedIndex === index || draggedTab === null) return

    // Determine the actual drop index based on the mouse position
    const tabElement = tabRefs.current[index]
    if (tabElement) {
      const rect = tabElement.getBoundingClientRect()
      const mouseX = e.clientX

      let dropIndex = index

      // If dropping on the right half of a tab, increment the index
      if (mouseX > rect.left + rect.width / 2) {
        dropIndex += 1
      }

      // Adjust for the case where we're moving from left to right
      if (draggedIndex < dropIndex) {
        dropIndex -= 1
      }

      // Reorder the tabs
      reorderTabs(draggedIndex, dropIndex)
    }

    // Reset drag state
    setDraggedTab(null)
    setDraggedIndex(-1)
    setIsDragging(false)
  }

  const handleDragEnd = (): void => {
    setDraggedTab(null)
    setDraggedIndex(-1)
    setIsDragging(false)
  }

  return (
    <div className="tabs-container">
      <button
        className={`home-button ${isHomeActive ? 'active' : ''}`}
        title="Home"
        onClick={handleHomeClick}
      >
        Home
      </button>

      <div className="tabs-rows-container">
        {showScrollButtons && (
          <button className="tab-scroll-button tab-scroll-left" onClick={scrollLeft}>
            &lt;
          </button>
        )}

        <div className="tabs-scroll-area" ref={tabsContainerRef}>
          {/* Drop indicator */}
          {isDragging && (
            <div className="drop-indicator" style={{ left: `${dropIndicatorLeft}px` }}></div>
          )}

          {tabs.map((tab, index) => (
            <div
              key={tab.id}
              ref={(el) => (tabRefs.current[index] = el)}
              className={`tab ${tab.id === activeTabId && !isHomeActive ? 'active' : ''} ${isHomeActive ? 'inactive' : ''} ${draggedTab === tab.id ? 'dragging' : ''}`}
              draggable="true"
              onClick={() => handleTabClick(tab.id)}
              onContextMenu={(e) => handleContextMenu(e, tab.id)}
              onDragStart={(e) => handleDragStart(e, tab.id, index)}
              onDragOver={(e) => handleDragOver(e, tab.id, index)}
              onDrop={(e) => handleDrop(e, index)}
              onDragEnd={handleDragEnd}
            >
              <div className="tab-title">{tab.title}</div>
              <div className="tab-close" onClick={(e) => handleCloseTab(e, tab.id)}>
                ✕
              </div>
            </div>
          ))}
        </div>

        {showScrollButtons && (
          <button className="tab-scroll-button tab-scroll-right" onClick={scrollRight}>
            &gt;
          </button>
        )}
      </div>

      {/* Context Menu */}
      {contextMenuVisible && contextMenuTabId && (
        <div
          className="tab-context-menu"
          style={{
            top: `${contextMenuPosition.y}px`,
            left: `${contextMenuPosition.x}px`
          }}
        >
          <div
            className="context-menu-item"
            onClick={() => {
              closeTab(contextMenuTabId)
              setContextMenuVisible(false)
            }}
          >
            Close
          </div>
          <div className="context-menu-item" onClick={handleCloseOtherTabs}>
            Close Others
          </div>
          <div className="context-menu-item" onClick={handleCloseTabsToRight}>
            Close Tabs to the Right
          </div>
          <div className="context-menu-item" onClick={handleCloseAllTabs}>
            Close All
          </div>
        </div>
      )}
    </div>
  )
}

export default TabBar
