// src/components/TabBar.tsx
import React from 'react';
import { useStore } from '../store/useStore';
import '../styles/TabBar.css';

const TabBar: React.FC = () => {
  const { tabs, activeTabId, addTab, closeTab, setActiveTab } = useStore();

  const handleAddTab = () => {
    addTab({
      title: 'New Tab',
      content: '',
      path: null,
      isModified: false,
    });
  };

  const handleCloseTab = (e: React.MouseEvent, id: string) => {
    e.stopPropagation();
    closeTab(id);
  };

  const handleTabClick = (id: string) => {
    setActiveTab(id);
  };

  return (
    <div className="tab-container">
      <div className="tabs">
        {tabs.map((tab) => (
          <div
            key={tab.id}
            className={`tab ${activeTabId === tab.id ? 'active' : ''}`}
            onClick={() => handleTabClick(tab.id)}
          >
            <span className="tab-title">
              {tab.title}
              {tab.isModified && ' *'}
            </span>
            <button
              className="tab-close"
              onClick={(e) => handleCloseTab(e, tab.id)}
              aria-label="Close tab"
            >
              ×
            </button>
          </div>
        ))}
      </div>
      <button
        className="add-tab-button"
        onClick={handleAddTab}
        aria-label="Add new tab"
      >
        +
      </button>
    </div>
  );
};

export default TabBar;

// src/renderer/src/components/TabBar.vue
<template>
  <div class="tabs">
    <div v-for="tab in tabs" :key="tab.id" class="tab" :class="{ active: tab.id === activeTabId }"
      @click="setActiveTab(tab.id)">
      <div class="tab-title">
        {{ tab.title }}{{ tab.isUnsaved ? '*' : '' }}
      </div>
      <div class="tab-close" @click.stop="closeTab(tab.id)">✕</div>
    </div>
    <button class="new-tab-button" @click="createNewTab">+</button>
  </div>
</template>

<script setup>
import { computed } from 'vue'
import { useTabsStore } from '../store/tabsStore'

// Get the tabs store
const tabsStore = useTabsStore()

// Computed properties for tabs and active tab
const tabs = computed(() => tabsStore.tabs)
const activeTabId = computed(() => tabsStore.activeTabId)

// Methods
const setActiveTab = (tabId) => {
  tabsStore.setActiveTab(tabId)
}

const closeTab = (tabId) => {
  tabsStore.closeTab(tabId)
}

const createNewTab = () => {
  tabsStore.addTab({
    title: 'Untitled',
    content: '',
    isUnsaved: true
  })
}
</script>

<style scoped>
/* Tab styling is in global.css */
</style>
