// src/renderer/src/components/TopNavBar.tsx
import React, { useState, useEffect, useRef, useCallback } from 'react'
import { useAppStore } from '../stores/appStore'
import './TopNavBar.css'

interface TopNavBarProps {
  onMenuAction: (menuAction: string) => void
  onOpenSettings: () => void
}

const TopNavBar: React.FC<TopNavBarProps> = ({
  onMenuAction,
  onOpenSettings
}): React.ReactElement => {
  // Get state from the app store
  const { activeTabId } = useAppStore()

  // Menu state
  const [activeMenu, setActiveMenu] = useState('')
  const [menuClicked, setMenuClicked] = useState(false)

  // Refs for menu containers
  const fileMenuRef = useRef<HTMLDivElement>(null)
  const helpMenuRef = useRef<HTMLDivElement>(null)

  // Toggle menu visibility
  const toggleMenu = (menu: string): void => {
    setActiveMenu(activeMenu === menu ? '' : menu)
    setMenuClicked(activeMenu !== menu)
  }

  // Close all menus
  const closeAllMenus = useCallback((): void => {
    setActiveMenu('')
    setMenuClicked(false)
  }, [])

  // Handle click outside to close menus
  useEffect(() => {
    const handleOutsideClick = (event: MouseEvent): void => {
      const isMenuClick = (event.target as Element).closest('.menu-container')
      const isTopNavClick = (event.target as Element).closest('.top-nav')

      // Close menus when clicking outside menu containers
      if (!isMenuClick) {
        closeAllMenus()
      }

      // Reset hover behavior when clicking outside the top nav
      if (!isTopNavClick) {
        setMenuClicked(false)
      }
    }

    // Add event listener
    document.addEventListener('click', handleOutsideClick)

    // Clean up
    return (): void => {
      document.removeEventListener('click', handleOutsideClick)
    }
  }, [closeAllMenus]) // Dependency on closeAllMenus

  // Handle keyboard shortcuts
  useEffect(() => {
    const handleKeyDown = (event: KeyboardEvent): void => {
      // Check for keyboard shortcuts
      if (event.ctrlKey || event.metaKey) {
        switch (event.key.toLowerCase()) {
          case 'x': // Ctrl+X: Cut
            // Let the browser handle this
            break
          case 'c': // Ctrl+C: Copy
            // Let the browser handle this
            break
          case 'v': // Ctrl+V: Paste
            // Let the browser handle this
            break
          case ',': // Ctrl+Comma: Settings
            event.preventDefault()
            onOpenSettings()
            break
        }
      } else if (event.key === 'Escape') {
        // Escape key closes all menus
        closeAllMenus()
      }
    }

    // Add event listener
    window.addEventListener('keydown', handleKeyDown)

    // Clean up
    return (): void => {
      window.removeEventListener('keydown', handleKeyDown)
    }
  }, [activeTabId, onOpenSettings, closeAllMenus]) // Re-run when dependencies change

  // Handle menu actions
  const handleMenuAction = (menuAction: string): void => {
    closeAllMenus()
    onMenuAction(menuAction)
  }

  // File operations have been removed

  // No edit operations - removed

  return (
    <div className="top-nav" ref={fileMenuRef}>
      {/* File Menu */}
      <div className="menu-container">
        <div
          className="top-nav-item"
          onClick={() => toggleMenu('file')}
          onMouseEnter={() => (menuClicked ? setActiveMenu('file') : null)}
        >
          File
        </div>
        {activeMenu === 'file' && (
          <div className="menu">
            {/* File operations have been removed */}
            <div className="menu-item" onClick={() => handleMenuAction('settings')}>
              <span>Settings</span>
            </div>
            <div className="menu-item" onClick={() => window.api.closeWindow()}>
              <span>Exit</span>
            </div>
          </div>
        )}
      </div>

      {/* Edit Menu has been removed */}

      {/* Help Menu */}
      <div className="menu-container" ref={helpMenuRef}>
        <div
          className="top-nav-item"
          onClick={() => toggleMenu('help')}
          onMouseEnter={() => (menuClicked ? setActiveMenu('help') : null)}
        >
          Help
        </div>
        {activeMenu === 'help' && (
          <div className="menu">
            <div className="menu-item" onClick={() => handleMenuAction('about')}>
              <span>About Textonom</span>
            </div>
            <div
              className="menu-item"
              onClick={() => {
                closeAllMenus()
                window.open('https://github.com/Netroforge/textonom', '_blank')
              }}
            >
              <span>GitHub Repository</span>
            </div>
            <div className="menu-item" onClick={() => handleMenuAction('checkForUpdates')}>
              <span>Check for Updates</span>
            </div>
          </div>
        )}
      </div>
    </div>
  )
}

export default TopNavBar

// src/renderer/src/components/TopNavBar.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted } from 'vue'
import './TopNavBar.css'

const props = defineProps<{
  onMenuAction: (menuAction: string) => void
  onOpenSettings: () => void
}>()

const activeMenu = ref('')
const menuClicked = ref(false)

const toggleMenu = (menu: string): void => {
  if (activeMenu.value === menu) {
    activeMenu.value = ''
    menuClicked.value = false
  } else {
    activeMenu.value = menu
    menuClicked.value = true
  }
}

const closeAllMenus = (): void => {
  activeMenu.value = ''
  menuClicked.value = false
}

const handleOutsideClick = (event: MouseEvent): void => {
  const target = event.target as Element
  const isMenuClick = target.closest('.menu-container')
  const isTopNavClick = target.closest('.top-nav')

  if (!isMenuClick) closeAllMenus()
  if (!isTopNavClick) menuClicked.value = false
}

const handleKeyDown = (event: KeyboardEvent): void => {
  if (event.ctrlKey || event.metaKey) {
    if (event.key.toLowerCase() === ',') {
      event.preventDefault()
      props.onOpenSettings()
    }
  } else if (event.key === 'Escape') {
    closeAllMenus()
  }
}

onMounted(() => {
  document.addEventListener('click', handleOutsideClick)
  window.addEventListener('keydown', handleKeyDown)
})

onUnmounted(() => {
  document.removeEventListener('click', handleOutsideClick)
  window.removeEventListener('keydown', handleKeyDown)
})

const handleMenuAction = (menuAction: string): void => {
  closeAllMenus()
  props.onMenuAction(menuAction)
}

const handleHover = (menu: string): void => {
  if (menuClicked.value) {
    activeMenu.value = menu
  }
}

const exitApp = (): void => {
  window.api.closeWindow()
}

const openGithub = (): void => {
  closeAllMenus()
  window.open('https://github.com/Netroforge/textonom', '_blank')
}
</script>

<template>
  <div class="top-nav">
    <div class="menu-container">
      <div class="top-nav-item" @click="toggleMenu('file')" @mouseenter="handleHover('file')">
        File
      </div>
      <div v-if="activeMenu === 'file'" class="menu">
        <div class="menu-item" @click="handleMenuAction('settings')">
          <span>Settings</span>
        </div>
        <div class="menu-item" @click="exitApp">
          <span>Exit</span>
        </div>
      </div>
    </div>

    <div class="menu-container">
      <div class="top-nav-item" @click="toggleMenu('help')" @mouseenter="handleHover('help')">
        Help
      </div>
      <div v-if="activeMenu === 'help'" class="menu">
        <div class="menu-item" @click="handleMenuAction('about')">
          <span>About Textonom</span>
        </div>
        <div class="menu-item" @click="openGithub">
          <span>GitHub Repository</span>
        </div>
        <div class="menu-item" @click="openGithub">
          <span>Star on GitHub</span>
        </div>
        <div class="menu-item" @click="handleMenuAction('checkForUpdates')">
          <span>Check for Updates</span>
        </div>
      </div>
    </div>
  </div>
</template>
