// src/renderer/src/components/Versions.tsx
import React, { useState, useEffect } from 'react'
import './Versions.css'

const Versions: React.FC = () => {
  const [versions, setVersions] = useState<Record<string, string>>({})

  useEffect(() => {
    // Get versions from electron
    const getVersions = async (): Promise<void> => {
      try {
        const appVersion = await window.api.getAppVersion()
        setVersions({
          app: appVersion,
          electron: process.versions.electron || '',
          chrome: process.versions.chrome || '',
          node: process.versions.node || ''
        })
      } catch (error) {
        console.error('Failed to get versions:', error)
      }
    }

    getVersions()
  }, [])

  return (
    <div className="versions">
      <div className="version-item">
        <span className="version-label">App:</span>
        <span className="version-value">{versions.app}</span>
      </div>
      <div className="version-item">
        <span className="version-label">Electron:</span>
        <span className="version-value">{versions.electron}</span>
      </div>
      <div className="version-item">
        <span className="version-label">Chrome:</span>
        <span className="version-value">{versions.chrome}</span>
      </div>
      <div className="version-item">
        <span className="version-label">Node:</span>
        <span className="version-value">{versions.node}</span>
      </div>
    </div>
  )
}

export default Versions

// src/renderer/src/components/Versions.vue
<script setup lang="ts">
import { ref, onMounted } from 'vue'
import './Versions.css'

const versions = ref<Record<string, string>>({})

onMounted(async () => {
  try {
    const appVersion = await window.api.getAppVersion()
    versions.value = {
      app: appVersion,
      electron: process.versions.electron || '',
      chrome: process.versions.chrome || '',
      node: process.versions.node || ''
    }
  } catch (error) {
    console.error('Failed to get versions:', error)
  }
})
</script>

<template>
  <div class="versions">
    <div class="version-item">
      <span class="version-label">App:</span>
      <span class="version-value">{{ versions.app }}</span>
    </div>
    <div class="version-item">
      <span class="version-label">Electron:</span>
      <span class="version-value">{{ versions.electron }}</span>
    </div>
    <div class="version-item">
      <span class="version-label">Chrome:</span>
      <span class="version-value">{{ versions.chrome }}</span>
    </div>
    <div class="version-item">
      <span class="version-label">Node:</span>
      <span class="version-value">{{ versions.node }}</span>
    </div>
  </div>
</template>
