// src/renderer/src/components/transformations/Base64EncodePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { base64Encode } from '../../transformations/base64'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => base64Encode(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Base64 Encode"
    transformation-description="Encode text to Base64 format"
    input-placeholder="Enter text to encode to Base64..."
    output-placeholder="Base64 encoded text will appear here..."
    transform-button-text="Encode"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/Base64EncodePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { base64Encode } from '../../transformations/base64'

interface Base64EncodePageProps {
  tabId: string
}

const Base64EncodePage: React.FC<Base64EncodePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Base64 Encode"
      transformationDescription="Encode text to Base64 format"
      inputPlaceholder="Enter text to encode to Base64..."
      outputPlaceholder="Base64 encoded text will appear here..."
      transformButtonText="Encode"
      transformFunction={async (text) => base64Encode(text)}
    />
  )
}

export default Base64EncodePage
