// src/renderer/src/components/transformations/Base64DecodePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { base64Decode } from '../../transformations/base64'

interface Base64DecodePageProps {
  tabId: string
}

const Base64DecodePage: React.FC<Base64DecodePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Base64 Decode"
      transformationDescription="Decode Base64 encoded text"
      inputPlaceholder="Enter Base64 encoded text to decode..."
      outputPlaceholder="Decoded text will appear here..."
      transformButtonText="Decode"
      transformFunction={async (text) => base64Decode(text)}
    />
  )
}

export default Base64DecodePage

// src/renderer/src/components/transformations/Base64DecodePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { base64Decode } from '../../transformations/base64'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => base64Decode(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Base64 Decode"
    transformation-description="Decode Base64 encoded text"
    input-placeholder="Enter Base64 encoded text to decode..."
    output-placeholder="Decoded text will appear here..."
    transform-button-text="Decode"
    :transform-function="transform"
  />
</template>
