// src/renderer/src/components/transformations/DeduplicateLinesPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { deduplicateLines } from '../../transformations/lines'

interface DeduplicateLinesPageProps {
  tabId: string
}

const DeduplicateLinesPage: React.FC<DeduplicateLinesPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Deduplicate Lines"
      transformationDescription="Remove duplicate lines"
      inputPlaceholder="Enter text with duplicate lines to remove..."
      outputPlaceholder="Deduplicated lines will appear here..."
      transformButtonText="Deduplicate"
      transformFunction={async (text) => deduplicateLines(text)}
    />
  )
}

export default DeduplicateLinesPage

// src/renderer/src/components/transformations/DeduplicateLinesPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { deduplicateLines } from '../../transformations/lines'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => deduplicateLines(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Deduplicate Lines"
    transformation-description="Remove duplicate lines"
    input-placeholder="Enter text with duplicate lines to remove..."
    output-placeholder="Deduplicated lines will appear here..."
    transform-button-text="Deduplicate"
    :transform-function="transform"
  />
</template>
