// src/renderer/src/components/transformations/HexDecodePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { hexDecode } from '../../transformations/hex'

interface HexDecodePageProps {
  tabId: string
}

const HexDecodePage: React.FC<HexDecodePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Hex Decode"
      transformationDescription="Decode hexadecimal text to plain text"
      inputPlaceholder="Enter hexadecimal text to decode..."
      outputPlaceholder="Decoded text will appear here..."
      transformButtonText="Decode"
      transformFunction={async (text) => hexDecode(text)}
    />
  )
}

export default HexDecodePage

// src/renderer/src/components/transformations/HexDecodePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { hexDecode } from '../../transformations/hex'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => hexDecode(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Hex Decode"
    transformation-description="Decode hexadecimal text to plain text"
    input-placeholder="Enter hexadecimal text to decode..."
    output-placeholder="Decoded text will appear here..."
    transform-button-text="Decode"
    :transform-function="transform"
  />
</template>
