// src/renderer/src/components/transformations/HexEncodePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { hexEncode } from '../../transformations/hex'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => hexEncode(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Hex Encode"
    transformation-description="Encode text to hexadecimal representation"
    input-placeholder="Enter text to encode to hexadecimal..."
    output-placeholder="Hexadecimal encoded text will appear here..."
    transform-button-text="Encode"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/HexEncodePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { hexEncode } from '../../transformations/hex'

interface HexEncodePageProps {
  tabId: string
}

const HexEncodePage: React.FC<HexEncodePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Hex Encode"
      transformationDescription="Encode text to hexadecimal representation"
      inputPlaceholder="Enter text to encode to hexadecimal..."
      outputPlaceholder="Hexadecimal encoded text will appear here..."
      transformButtonText="Encode"
      transformFunction={async (text) => hexEncode(text)}
    />
  )
}

export default HexEncodePage
