// src/renderer/src/components/transformations/HtmlEncodePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { htmlEncode } from '../../transformations/html'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => htmlEncode(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="HTML Encode"
    transformation-description="Encode special characters for HTML"
    input-placeholder="Enter text to HTML encode..."
    output-placeholder="HTML encoded text will appear here..."
    transform-button-text="Encode"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/HtmlEncodePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { htmlEncode } from '../../transformations/html'

interface HtmlEncodePageProps {
  tabId: string
}

const HtmlEncodePage: React.FC<HtmlEncodePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="HTML Encode"
      transformationDescription="Encode special characters for HTML"
      inputPlaceholder="Enter text to HTML encode..."
      outputPlaceholder="HTML encoded text will appear here..."
      transformButtonText="Encode"
      transformFunction={async (text) => htmlEncode(text)}
    />
  )
}

export default HtmlEncodePage
