// src/renderer/src/components/transformations/HtmlDecodePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { htmlDecode } from '../../transformations/html'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => htmlDecode(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="HTML Decode"
    transformation-description="Decode HTML encoded text"
    input-placeholder="Enter HTML encoded text to decode..."
    output-placeholder="Decoded text will appear here..."
    transform-button-text="Decode"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/HtmlDecodePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { htmlDecode } from '../../transformations/html'

interface HtmlDecodePageProps {
  tabId: string
}

const HtmlDecodePage: React.FC<HtmlDecodePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="HTML Decode"
      transformationDescription="Decode HTML encoded text"
      inputPlaceholder="Enter HTML encoded text to decode..."
      outputPlaceholder="Decoded text will appear here..."
      transformButtonText="Decode"
      transformFunction={async (text) => htmlDecode(text)}
    />
  )
}

export default HtmlDecodePage
