// src/renderer/src/components/transformations/JsonPrettifyPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { jsonPrettify } from '../../transformations/json'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => jsonPrettify(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="JSON Prettify"
    transformation-description="Format JSON with proper indentation"
    input-placeholder="Enter JSON to format..."
    output-placeholder="Formatted JSON will appear here..."
    transform-button-text="Format"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/JsonPrettifyPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { jsonPrettify } from '../../transformations/json'

interface JsonPrettifyPageProps {
  tabId: string
}

const JsonPrettifyPage: React.FC<JsonPrettifyPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="JSON Prettify"
      transformationDescription="Format JSON with proper indentation"
      inputPlaceholder="Enter JSON to format..."
      outputPlaceholder="Formatted JSON will appear here..."
      transformButtonText="Format"
      transformFunction={async (text) => jsonPrettify(text)}
    />
  )
}

export default JsonPrettifyPage
