// src/renderer/src/components/transformations/JsonCompactPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { jsonCompact } from '../../transformations/json'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => jsonCompact(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="JSON Compact"
    transformation-description="Compact JSON by removing whitespace"
    input-placeholder="Enter JSON to compact..."
    output-placeholder="Compacted JSON will appear here..."
    transform-button-text="Compact"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/JsonCompactPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { jsonCompact } from '../../transformations/json'

interface JsonCompactPageProps {
  tabId: string
}

const JsonCompactPage: React.FC<JsonCompactPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="JSON Compact"
      transformationDescription="Compact JSON by removing whitespace"
      inputPlaceholder="Enter JSON to compact..."
      outputPlaceholder="Compacted JSON will appear here..."
      transformButtonText="Compact"
      transformFunction={async (text) => jsonCompact(text)}
    />
  )
}

export default JsonCompactPage
