// src/renderer/src/components/transformations/JsonToYamlPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { jsonToYaml } from '../../transformations/conversion'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => jsonToYaml(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="JSON to YAML"
    transformation-description="Convert JSON to YAML format"
    input-placeholder="Enter JSON to convert to YAML..."
    output-placeholder="YAML will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/JsonToYamlPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { jsonToYaml } from '../../transformations/conversion'

interface JsonToYamlPageProps {
  tabId: string
}

const JsonToYamlPage: React.FC<JsonToYamlPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="JSON to YAML"
      transformationDescription="Convert JSON to YAML format"
      inputPlaceholder="Enter JSON to convert to YAML..."
      outputPlaceholder="YAML will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => jsonToYaml(text)}
    />
  )
}

export default JsonToYamlPage
