// src/renderer/src/components/transformations/JwtDecodePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { jwtDecode } from '../../transformations/jwt'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => jwtDecode(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="JWT Decode"
    transformation-description="Decode JSON Web Token (JWT) to view its contents"
    input-placeholder="Enter JWT token to decode..."
    output-placeholder="Decoded JWT content will appear here..."
    transform-button-text="Decode"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/JwtDecodePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { jwtDecode } from '../../transformations/jwt'

interface JwtDecodePageProps {
  tabId: string
}

const JwtDecodePage: React.FC<JwtDecodePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="JWT Decode"
      transformationDescription="Decode JSON Web Token (JWT) to view its contents"
      inputPlaceholder="Enter JWT token to decode..."
      outputPlaceholder="Decoded JWT content will appear here..."
      transformButtonText="Decode"
      transformFunction={async (text) => jwtDecode(text)}
    />
  )
}

export default JwtDecodePage
