// src/renderer/src/components/transformations/MarkdownToHtmlPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { markdownToHtml } from '../../transformations/markdown'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => markdownToHtml(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Markdown to HTML"
    transformation-description="Convert Markdown text to HTML"
    input-placeholder="Enter Markdown text to convert to HTML..."
    output-placeholder="HTML output will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/MarkdownToHtmlPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { markdownToHtml } from '../../transformations/markdown'

interface MarkdownToHtmlPageProps {
  tabId: string
}

const MarkdownToHtmlPage: React.FC<MarkdownToHtmlPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Markdown to HTML"
      transformationDescription="Convert Markdown text to HTML"
      inputPlaceholder="Enter Markdown text to convert to HTML..."
      outputPlaceholder="HTML output will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => markdownToHtml(text)}
    />
  )
}

export default MarkdownToHtmlPage
