// src/renderer/src/components/transformations/Md5HashPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { md5Hash } from '../../transformations/hash'

interface Md5HashPageProps {
  tabId: string
}

const Md5HashPage: React.FC<Md5HashPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="MD5 Hash"
      transformationDescription="Generate MD5 hash of text"
      inputPlaceholder="Enter text to hash..."
      outputPlaceholder="MD5 hash will appear here..."
      transformButtonText="Hash"
      transformFunction={async (text) => md5Hash(text)}
    />
  )
}

export default Md5HashPage

// src/renderer/src/components/transformations/Md5HashPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { md5Hash } from '../../transformations/hash'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => md5Hash(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="MD5 Hash"
    transformation-description="Generate MD5 hash of text"
    input-placeholder="Enter text to hash..."
    output-placeholder="MD5 hash will appear here..."
    transform-button-text="Hash"
    :transform-function="transform"
  />
</template>
