// src/renderer/src/components/transformations/PropertiesFileToYamlPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { propertiesFileToYaml } from '../../transformations/conversion'

interface PropertiesFileToYamlPageProps {
  tabId: string
}

const PropertiesFileToYamlPage: React.FC<PropertiesFileToYamlPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Properties to YAML"
      transformationDescription="Convert Java properties file to YAML"
      inputPlaceholder="Enter properties file content to convert to YAML..."
      outputPlaceholder="YAML will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => propertiesFileToYaml(text)}
    />
  )
}

export default PropertiesFileToYamlPage

// src/renderer/src/components/transformations/PropertiesFileToYamlPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { propertiesFileToYaml } from '../../transformations/conversion'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => propertiesFileToYaml(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Properties to YAML"
    transformation-description="Convert Java properties file to YAML"
    input-placeholder="Enter properties file content to convert to YAML..."
    output-placeholder="YAML will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>
