// src/renderer/src/components/transformations/RemoveEmptyLinesPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { removeEmptyLines } from '../../transformations/lines'

interface RemoveEmptyLinesPageProps {
  tabId: string
}

const RemoveEmptyLinesPage: React.FC<RemoveEmptyLinesPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Remove Empty Lines"
      transformationDescription="Remove all empty lines from text"
      inputPlaceholder="Enter text with empty lines to remove..."
      outputPlaceholder="Text with empty lines removed will appear here..."
      transformButtonText="Remove Empty Lines"
      transformFunction={async (text) => removeEmptyLines(text)}
    />
  )
}

export default RemoveEmptyLinesPage

// src/renderer/src/components/transformations/RemoveEmptyLinesPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { removeEmptyLines } from '../../transformations/lines'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => removeEmptyLines(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Remove Empty Lines"
    transformation-description="Remove all empty lines from text"
    input-placeholder="Enter text with empty lines to remove..."
    output-placeholder="Text with empty lines removed will appear here..."
    transform-button-text="Remove Empty Lines"
    :transform-function="transform"
  />
</template>
