// src/renderer/src/components/transformations/RemoveDuplicateWordsPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { removeDuplicateWords } from '../../transformations/text'

interface RemoveDuplicateWordsPageProps {
  tabId: string
}

const RemoveDuplicateWordsPage: React.FC<RemoveDuplicateWordsPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Remove Duplicate Words"
      transformationDescription="Remove duplicate words from text (case-insensitive)"
      inputPlaceholder="Enter text with duplicate words to remove..."
      outputPlaceholder="Text with duplicate words removed will appear here..."
      transformButtonText="Remove Duplicates"
      transformFunction={async (text) => removeDuplicateWords(text)}
    />
  )
}

export default RemoveDuplicateWordsPage

// src/renderer/src/components/transformations/RemoveDuplicateWordsPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { removeDuplicateWords } from '../../transformations/text'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => removeDuplicateWords(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Remove Duplicate Words"
    transformation-description="Remove duplicate words from text (case-insensitive)"
    input-placeholder="Enter text with duplicate words to remove..."
    output-placeholder="Text with duplicate words removed will appear here..."
    transform-button-text="Remove Duplicates"
    :transform-function="transform"
  />
</template>
