// src/renderer/src/components/transformations/ReverseLinesPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { reverseLines } from '../../transformations/lines'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => reverseLines(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Reverse Lines"
    transformation-description="Reverse the order of lines"
    input-placeholder="Enter text with multiple lines to reverse..."
    output-placeholder="Reversed lines will appear here..."
    transform-button-text="Reverse"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/ReverseLinesPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { reverseLines } from '../../transformations/lines'

interface ReverseLinesPageProps {
  tabId: string
}

const ReverseLinesPage: React.FC<ReverseLinesPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Reverse Lines"
      transformationDescription="Reverse the order of lines"
      inputPlaceholder="Enter text with multiple lines to reverse..."
      outputPlaceholder="Reversed lines will appear here..."
      transformButtonText="Reverse"
      transformFunction={async (text) => reverseLines(text)}
    />
  )
}

export default ReverseLinesPage
