// src/renderer/src/components/transformations/Sha1HashPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { sha1Hash } from '../../transformations/hash'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => sha1Hash(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="SHA-1 Hash"
    transformation-description="Generate SHA-1 hash of text"
    input-placeholder="Enter text to hash..."
    output-placeholder="SHA-1 hash will appear here..."
    transform-button-text="Hash"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/Sha1HashPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { sha1Hash } from '../../transformations/hash'

interface Sha1HashPageProps {
  tabId: string
}

const Sha1HashPage: React.FC<Sha1HashPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="SHA-1 Hash"
      transformationDescription="Generate SHA-1 hash of text"
      inputPlaceholder="Enter text to hash..."
      outputPlaceholder="SHA-1 hash will appear here..."
      transformButtonText="Hash"
      transformFunction={async (text) => sha1Hash(text)}
    />
  )
}

export default Sha1HashPage
