// src/renderer/src/components/transformations/Sha256HashPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { sha256Hash } from '../../transformations/hash'

interface Sha256HashPageProps {
  tabId: string
}

const Sha256HashPage: React.FC<Sha256HashPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="SHA-256 Hash"
      transformationDescription="Generate SHA-256 hash of text"
      inputPlaceholder="Enter text to hash..."
      outputPlaceholder="SHA-256 hash will appear here..."
      transformButtonText="Hash"
      transformFunction={async (text) => sha256Hash(text)}
    />
  )
}

export default Sha256HashPage

// src/renderer/src/components/transformations/Sha256HashPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { sha256Hash } from '../../transformations/hash'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => sha256Hash(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="SHA-256 Hash"
    transformation-description="Generate SHA-256 hash of text"
    input-placeholder="Enter text to hash..."
    output-placeholder="SHA-256 hash will appear here..."
    transform-button-text="Hash"
    :transform-function="transform"
  />
</template>
