// src/renderer/src/components/transformations/Sha512HashPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { sha512Hash } from '../../transformations/hash'

interface Sha512HashPageProps {
  tabId: string
}

const Sha512HashPage: React.FC<Sha512HashPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="SHA-512 Hash"
      transformationDescription="Generate SHA-512 hash of text (stronger than SHA-256)"
      inputPlaceholder="Enter text to hash..."
      outputPlaceholder="SHA-512 hash will appear here..."
      transformButtonText="Hash"
      transformFunction={async (text) => sha512Hash(text)}
    />
  )
}

export default Sha512HashPage

// src/renderer/src/components/transformations/Sha512HashPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { sha512Hash } from '../../transformations/hash'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => sha512Hash(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="SHA-512 Hash"
    transformation-description="Generate SHA-512 hash of text (stronger than SHA-256)"
    input-placeholder="Enter text to hash..."
    output-placeholder="SHA-512 hash will appear here..."
    transform-button-text="Hash"
    :transform-function="transform"
  />
</template>
