// src/renderer/src/components/transformations/SortLinesPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { sortLines } from '../../transformations/lines'

interface SortLinesPageProps {
  tabId: string
}

const SortLinesPage: React.FC<SortLinesPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Sort Lines"
      transformationDescription="Sort lines alphabetically"
      inputPlaceholder="Enter text with multiple lines to sort..."
      outputPlaceholder="Sorted lines will appear here..."
      transformButtonText="Sort"
      transformFunction={async (text) => sortLines(text)}
    />
  )
}

export default SortLinesPage

// src/renderer/src/components/transformations/SortLinesPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { sortLines } from '../../transformations/lines'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => sortLines(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Sort Lines"
    transformation-description="Sort lines alphabetically"
    input-placeholder="Enter text with multiple lines to sort..."
    output-placeholder="Sorted lines will appear here..."
    transform-button-text="Sort"
    :transform-function="transform"
  />
</template>
