// src/renderer/src/components/transformations/ToCamelCasePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { toCamelCase } from '../../transformations/case'

interface ToCamelCasePageProps {
  tabId: string
}

const ToCamelCasePage: React.FC<ToCamelCasePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="To camelCase"
      transformationDescription="Convert text to camelCase (no spaces, first word lowercase, others capitalized)"
      inputPlaceholder="Enter text to convert to camelCase..."
      outputPlaceholder="Text in camelCase will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => toCamelCase(text)}
    />
  )
}

export default ToCamelCasePage

// src/renderer/src/components/transformations/ToCamelCasePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { toCamelCase } from '../../transformations/case'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => toCamelCase(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="To camelCase"
    transformation-description="Convert text to camelCase (no spaces, first word lowercase, others capitalized)"
    input-placeholder="Enter text to convert to camelCase..."
    output-placeholder="Text in camelCase will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>
