// src/renderer/src/components/transformations/ToKebabCasePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { toKebabCase } from '../../transformations/case'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => toKebabCase(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="To kebab-case"
    transformation-description="Convert text to kebab-case (lowercase with hyphens)"
    input-placeholder="Enter text to convert to kebab-case..."
    output-placeholder="Text in kebab-case will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/ToKebabCasePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { toKebabCase } from '../../transformations/case'

interface ToKebabCasePageProps {
  tabId: string
}

const ToKebabCasePage: React.FC<ToKebabCasePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="To kebab-case"
      transformationDescription="Convert text to kebab-case (lowercase with hyphens)"
      inputPlaceholder="Enter text to convert to kebab-case..."
      outputPlaceholder="Text in kebab-case will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => toKebabCase(text)}
    />
  )
}

export default ToKebabCasePage
