// src/renderer/src/components/transformations/ToLowerCasePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { toLowerCase } from '../../transformations/case'

interface ToLowerCasePageProps {
  tabId: string
}

const ToLowerCasePage: React.FC<ToLowerCasePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="To Lowercase"
      transformationDescription="Convert text to lowercase"
      inputPlaceholder="Enter text to convert to lowercase..."
      outputPlaceholder="Lowercase text will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => toLowerCase(text)}
    />
  )
}

export default ToLowerCasePage

// src/renderer/src/components/transformations/ToLowerCasePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { toLowerCase } from '../../transformations/case'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => toLowerCase(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="To Lowercase"
    transformation-description="Convert text to lowercase"
    input-placeholder="Enter text to convert to lowercase..."
    output-placeholder="Lowercase text will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>
