// src/renderer/src/components/transformations/ToSnakeCasePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { toSnakeCase } from '../../transformations/case'

interface ToSnakeCasePageProps {
  tabId: string
}

const ToSnakeCasePage: React.FC<ToSnakeCasePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="To snake_case"
      transformationDescription="Convert text to snake_case (lowercase with underscores)"
      inputPlaceholder="Enter text to convert to snake_case..."
      outputPlaceholder="Text in snake_case will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => toSnakeCase(text)}
    />
  )
}

export default ToSnakeCasePage

// src/renderer/src/components/transformations/ToSnakeCasePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { toSnakeCase } from '../../transformations/case'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => toSnakeCase(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="To snake_case"
    transformation-description="Convert text to snake_case (lowercase with underscores)"
    input-placeholder="Enter text to convert to snake_case..."
    output-placeholder="Text in snake_case will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>
