// src/renderer/src/components/transformations/ToTitleCasePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { toTitleCase } from '../../transformations/case'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => toTitleCase(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="To Title Case"
    transformation-description="Convert text to title case (first letter of each word capitalized)"
    input-placeholder="Enter text to convert to title case..."
    output-placeholder="Title case text will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/ToTitleCasePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { toTitleCase } from '../../transformations/case'

interface ToTitleCasePageProps {
  tabId: string
}

const ToTitleCasePage: React.FC<ToTitleCasePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="To Title Case"
      transformationDescription="Convert text to title case (first letter of each word capitalized)"
      inputPlaceholder="Enter text to convert to title case..."
      outputPlaceholder="Title case text will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => toTitleCase(text)}
    />
  )
}

export default ToTitleCasePage
