// src/renderer/src/components/transformations/ToUpperCasePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { toUpperCase } from '../../transformations/case'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => toUpperCase(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="To Uppercase"
    transformation-description="Convert text to uppercase"
    input-placeholder="Enter text to convert to uppercase..."
    output-placeholder="Uppercase text will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/ToUpperCasePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { toUpperCase } from '../../transformations/case'

interface ToUpperCasePageProps {
  tabId: string
}

const ToUpperCasePage: React.FC<ToUpperCasePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="To Uppercase"
      transformationDescription="Convert text to uppercase"
      inputPlaceholder="Enter text to convert to uppercase..."
      outputPlaceholder="Uppercase text will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => toUpperCase(text)}
    />
  )
}

export default ToUpperCasePage
