// src/renderer/src/components/transformations/UnicodeEscapePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { unicodeEscape } from '../../transformations/unicode'

interface UnicodeEscapePageProps {
  tabId: string
}

const UnicodeEscapePage: React.FC<UnicodeEscapePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Unicode Escape"
      transformationDescription="Escape Unicode characters to \\uXXXX format"
      inputPlaceholder="Enter text with Unicode characters to escape..."
      outputPlaceholder="Unicode escaped text will appear here..."
      transformButtonText="Escape"
      transformFunction={async (text) => unicodeEscape(text)}
    />
  )
}

export default UnicodeEscapePage

// src/renderer/src/components/transformations/UnicodeEscapePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { unicodeEscape } from '../../transformations/unicode'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => unicodeEscape(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Unicode Escape"
    transformation-description="Escape Unicode characters to \\uXXXX format"
    input-placeholder="Enter text with Unicode characters to escape..."
    output-placeholder="Unicode escaped text will appear here..."
    transform-button-text="Escape"
    :transform-function="transform"
  />
</template>
