// src/renderer/src/components/transformations/UnicodeUnescapePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { unicodeUnescape } from '../../transformations/unicode'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => unicodeUnescape(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="Unicode Unescape"
    transformation-description="Convert \\uXXXX format to actual Unicode characters"
    input-placeholder="Enter Unicode escaped text to unescape..."
    output-placeholder="Unicode unescaped text will appear here..."
    transform-button-text="Unescape"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/UnicodeUnescapePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { unicodeUnescape } from '../../transformations/unicode'

interface UnicodeUnescapePageProps {
  tabId: string
}

const UnicodeUnescapePage: React.FC<UnicodeUnescapePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="Unicode Unescape"
      transformationDescription="Convert \\uXXXX format to actual Unicode characters"
      inputPlaceholder="Enter Unicode escaped text to unescape..."
      outputPlaceholder="Unicode unescaped text will appear here..."
      transformButtonText="Unescape"
      transformFunction={async (text) => unicodeUnescape(text)}
    />
  )
}

export default UnicodeUnescapePage
