// src/renderer/src/components/transformations/UrlDecodePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { urlDecode } from '../../transformations/url'

interface UrlDecodePageProps {
  tabId: string
}

const UrlDecodePage: React.FC<UrlDecodePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="URL Decode"
      transformationDescription="Decode URL encoded text"
      inputPlaceholder="Enter URL encoded text to decode..."
      outputPlaceholder="Decoded text will appear here..."
      transformButtonText="Decode"
      transformFunction={async (text) => urlDecode(text)}
    />
  )
}

export default UrlDecodePage

// src/renderer/src/components/transformations/UrlDecodePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { urlDecode } from '../../transformations/url'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => urlDecode(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="URL Decode"
    transformation-description="Decode URL encoded text"
    input-placeholder="Enter URL encoded text to decode..."
    output-placeholder="Decoded text will appear here..."
    transform-button-text="Decode"
    :transform-function="transform"
  />
</template>
