// src/renderer/src/components/transformations/UrlEncodePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { urlEncode } from '../../transformations/url'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => urlEncode(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="URL Encode"
    transformation-description="Encode text for use in URLs"
    input-placeholder="Enter text to URL encode..."
    output-placeholder="URL encoded text will appear here..."
    transform-button-text="Encode"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/UrlEncodePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { urlEncode } from '../../transformations/url'

interface UrlEncodePageProps {
  tabId: string
}

const UrlEncodePage: React.FC<UrlEncodePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="URL Encode"
      transformationDescription="Encode text for use in URLs"
      inputPlaceholder="Enter text to URL encode..."
      outputPlaceholder="URL encoded text will appear here..."
      transformButtonText="Encode"
      transformFunction={async (text) => urlEncode(text)}
    />
  )
}

export default UrlEncodePage
