// src/renderer/src/components/transformations/XmlCompactPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { xmlCompact } from '../../transformations/xml'

interface XmlCompactPageProps {
  tabId: string
}

const XmlCompactPage: React.FC<XmlCompactPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="XML Compact"
      transformationDescription="Compact XML by removing whitespace"
      inputPlaceholder="Enter XML to compact..."
      outputPlaceholder="Compacted XML will appear here..."
      transformButtonText="Compact"
      transformFunction={async (text) => xmlCompact(text)}
    />
  )
}

export default XmlCompactPage

// src/renderer/src/components/transformations/XmlCompactPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { xmlCompact } from '../../transformations/xml'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => xmlCompact(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="XML Compact"
    transformation-description="Compact XML by removing whitespace"
    input-placeholder="Enter XML to compact..."
    output-placeholder="Compacted XML will appear here..."
    transform-button-text="Compact"
    :transform-function="transform"
  />
</template>
