// src/renderer/src/components/transformations/XmlPrettifyPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { xmlPrettify } from '../../transformations/xml'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => xmlPrettify(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="XML Prettify"
    transformation-description="Format XML with proper indentation"
    input-placeholder="Enter XML to format..."
    output-placeholder="Formatted XML will appear here..."
    transform-button-text="Format"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/XmlPrettifyPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { xmlPrettify } from '../../transformations/xml'

interface XmlPrettifyPageProps {
  tabId: string
}

const XmlPrettifyPage: React.FC<XmlPrettifyPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="XML Prettify"
      transformationDescription="Format XML with proper indentation"
      inputPlaceholder="Enter XML to format..."
      outputPlaceholder="Formatted XML will appear here..."
      transformButtonText="Format"
      transformFunction={async (text) => xmlPrettify(text)}
    />
  )
}

export default XmlPrettifyPage
