// src/renderer/src/components/transformations/YamlToJsonPage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { yamlToJson } from '../../transformations/conversion'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => yamlToJson(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="YAML to JSON"
    transformation-description="Convert YAML to JSON format"
    input-placeholder="Enter YAML to convert to JSON..."
    output-placeholder="JSON will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/YamlToJsonPage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { yamlToJson } from '../../transformations/conversion'

interface YamlToJsonPageProps {
  tabId: string
}

const YamlToJsonPage: React.FC<YamlToJsonPageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="YAML to JSON"
      transformationDescription="Convert YAML to JSON format"
      inputPlaceholder="Enter YAML to convert to JSON..."
      outputPlaceholder="JSON will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => yamlToJson(text)}
    />
  )
}

export default YamlToJsonPage
