// src/renderer/src/components/transformations/YamlToPropertiesFilePage.vue
<script setup lang="ts">
import BaseTransformationPage from './BaseTransformationPage.vue'
import { yamlToPropertiesFile } from '../../transformations/conversion'

defineProps<{ tabId: string }>()

const transform = async (text: string): Promise<string> => yamlToPropertiesFile(text)
</script>

<template>
  <BaseTransformationPage
    :tab-id="tabId"
    transformation-name="YAML to Properties"
    transformation-description="Convert YAML to Java properties file format"
    input-placeholder="Enter YAML to convert to properties file format..."
    output-placeholder="Properties file content will appear here..."
    transform-button-text="Convert"
    :transform-function="transform"
  />
</template>

// src/renderer/src/components/transformations/YamlToPropertiesFilePage.tsx
import React from 'react'
import BaseTransformationPage from './BaseTransformationPage'
import { yamlToPropertiesFile } from '../../transformations/conversion'

interface YamlToPropertiesFilePageProps {
  tabId: string
}

const YamlToPropertiesFilePage: React.FC<YamlToPropertiesFilePageProps> = ({ tabId }) => {
  return (
    <BaseTransformationPage
      tabId={tabId}
      transformationName="YAML to Properties"
      transformationDescription="Convert YAML to Java properties file format"
      inputPlaceholder="Enter YAML to convert to properties file format..."
      outputPlaceholder="Properties file content will appear here..."
      transformButtonText="Convert"
      transformFunction={async (text) => yamlToPropertiesFile(text)}
    />
  )
}

export default YamlToPropertiesFilePage
